### ISSUE TITLE
Hanging with parallel multi-processor futures

### ISSUE THREAD

**Issue by p1r473** [ambv/bitrot#41]
Hi
Ever since upgrading to 1.0 I have been getting the program to hang when trying to hash around 4tb on magnetic disks.
I am using `-w 1` for only one worker

I believe the current implementation of futures or the pool executor may be causing a deadlock or some sort of sleep condition.

However, multi-cpu processing is beyond my area of expertise
Anyone else hanging when trying to hash many terabytes of data?

If I kill it while its hung, I get this:
```
Traceback (most recent call last):
  File "c:\python3\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "c:\python3\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python3\lib\concurrent\futures\process.py", line 233, in _process_worker
    call_item = call_queue.get(block=True)
  File "c:\python3\lib\multiprocessing\queues.py", line 97, in get
    res = self._recv_bytes()
  File "c:\python3\lib\multiprocessing\connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "c:\python3\lib\multiprocessing\connection.py", line 305, in _recv_bytes
    waitres = _winapi.WaitForMultipleObjects(
KeyboardInterrupt
Traceback (most recent call last):
  File "C:\Startup\scripts\Bitrot\src\bitrot.py", line 1731, in <module>
  File "C:\Startup\scripts\Bitrot\src\bitrot.py", line 1725, in run_from_command_line

  File "C:\Startup\scripts\Bitrot\src\bitrot.py", line 810, in run
    for future in as_completed(futures):
  File "C:\Startup\scripts\Bitrot\src\bitrot.py", line 810, in <listcomp>
    for future in as_completed(futures):
  File "c:\python3\lib\concurrent\futures\process.py", line 643, in submit
    self._queue_management_thread_wakeup.wakeup()
  File "c:\python3\lib\concurrent\futures\process.py", line 90, in wakeup
    self._writer.send_bytes(b"")
  File "c:\python3\lib\multiprocessing\connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "c:\python3\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
KeyboardInterrupt
```

**Comment by p1r473** [comment]
I tried switching the pool executor
ProcessPoolExecutor runs each of your workers in its own separate child process.
ThreadPoolExecutor runs each of your workers in separate threads within the main process.
One hangs and one gives memory errors.
I think I will revert my fork back to single cpu.

**Comment by ambv** [comment]
Could

**Comment by p1r473** [comment]
Looks like its specific to my fork. Yours seems to be working.
I banged my head on this for many hours. Maybe I will take another stab at it, but not sure yet

**Comment by p1r473** [comment]
Have you thought of using ThreadPoolExecutor ?
All separate threads in same process.

**Comment by p1r473** [comment]
@ambv have you thought about multi-threading list_existing_paths()?
Besides hashing, this process takes a lot of time too.

**Comment by ambv** [comment]
Good idea, actually!
