### ISSUE TITLE
Rename handling logic broken

### ISSUE THREAD

**Issue by yang** [ambv/bitrot#6]
To be honest, I don't know why this rename handling logic is doing what it's doing, so you're probably the best person to remedy this since you probably at least know what it's *supposed* to be doing, but anyway I am regularly running into `column path is not unique` errors, which I've repro'd here just based on reading the code:

```
$ mkdir /tmp/bitrot/

$ cd /tmp/bitrot/

$ echo a > a

$ echo a > b

$ bitrot
Finished. 0.00 MiB of data read. 0 errors found.
2 entries in the database, 2 new, 0 updated, 0 renamed, 0 missing.

$ mv a c

$ mv b d

$ bitrot
 50.0%Traceback (most recent call last):
  File "/home/yang/.virtualenvs/bitrot/bin/bitrot", line 8, in <module>
    execfile(__file__)
  File "/home/yang/bitrot/bin/bitrot", line 30, in <module>
    run_from_command_line()
  File "/home/yang/bitrot/src/bitrot.py", line 265, in run_from_command_line
    chunk_size=args.chunk_size)
  File "/home/yang/bitrot/src/bitrot.py", line 151, in run
    (new_mtime, p_uni, update_ts, new_sha1))
sqlite3.IntegrityError: column path is not unique
```

**Comment by ambv** [comment]
Fixed in 0.7.0.
